
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/cmake-3.30.5-7ubmzhvg4bacu5sdnbddyv735ag6e5mq/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-127-generic - x86_64
...
