# CMake generated Testfile for 
# Source directory: /home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi
# Build directory: /home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[GlobalTreeTests]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/globaloctree")
set_tests_properties([=[GlobalTreeTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;19;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalHaloExchange]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/exchange_halos")
set_tests_properties([=[GlobalHaloExchange]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;20;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalBox]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/box_mpi")
set_tests_properties([=[GlobalBox]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;21;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalFocusExchange]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/exchange_focus")
set_tests_properties([=[GlobalFocusExchange]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;22;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalKeyExchange]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/exchange_keys")
set_tests_properties([=[GlobalKeyExchange]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;23;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[FocusTransfer]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/focus_transfer")
set_tests_properties([=[FocusTransfer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;24;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalDomain2Ranks]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/domain_2ranks")
set_tests_properties([=[GlobalDomain2Ranks]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;25;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalDomainResize]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "2" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/domain_resize")
set_tests_properties([=[GlobalDomainResize]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;26;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalDomainTreeIntregration]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "12" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/treedomain")
set_tests_properties([=[GlobalDomainTreeIntregration]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;28;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GeneralFocusExchange]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "12" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/exchange_general")
set_tests_properties([=[GeneralFocusExchange]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;29;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalDomainExchange]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "12" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/exchange_domain")
set_tests_properties([=[GlobalDomainExchange]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;30;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[FocusTreeIntregration]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "12" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/focus_tree")
set_tests_properties([=[FocusTreeIntregration]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;31;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
add_test([=[GlobalDomainNRanks]=] "/apps/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openmpi-4.1.3-efaqdqjshm5pznecwekvbmt42qbwhinl/bin/mpiexec" "-n" "12" "/home/lwatan/data/SPH-EXA-fork/build-version1/domain/test/integration_mpi/domain_nranks")
set_tests_properties([=[GlobalDomainNRanks]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lwatan/data/SPH-EXA-fork/domain/cmake/cstone_add_test.cmake;39;add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;10;cstone_add_test;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;16;addMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;32;addCstoneMpiTest;/home/lwatan/data/SPH-EXA-fork/domain/test/integration_mpi/CMakeLists.txt;0;")
